### Recupera todas las peliculas
GET http://localhost:1234/movies

### Recupera una pelicula por id
GET http://localhost:1234/movies/f13d11fc-6d49-11ef-ace5-04d4c4ade682

### Recupera peliculas por genero
GET http://localhost:1234/movies?genre=Action

### Añade pelicula nueva
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Attack on Titans",
    "year": 2009,
    "director": "Un japones",
    "duration": 300,
    "poster": "https://www.latercera.com/resizer/zgMdnEk2a1IOwi-NIqMS-fkRmKE=/arc-anglerfish-arc2-prod-copesa/public/O5P35GANJVCWZCRVI5EBJJ73GE.jpg",
    "genre": [ "Anime", "Drama" ],
    "rate": 9.9
}

### Actualiza pelicula existente
PATCH http://localhost:1234/movies/eedf1564-6d48-11ef-ace5-04d4c4ade682
Content-Type: application/json

{
    "director": "Seguro que un asiatico",
    "duration": 666
}


### Borrar pelicula
DELETE http://localhost:1234/movies/f13d11fc-6d49-11ef-ace5-04d4c4ade682